### ISSUE TITLE
Close orders automatically at the end of the day?

### ISSUE THREAD

**Issue by thakkarparth007** [delta/dalal-street-server#198]
The problem with this would be filling up the order book at the beginning of the new day again.
Alternatively, close orders at the end of two days. 

Alternatively/Additionally, provide different types of orders - "immediate or cancel", etc.

**Comment by PaiAkshay998** [comment]
I feel all 'Close Orders' issues will not be done for now. Since we are planning on adding a order fee for each order placed, I think it'd be unfair to charge people and then cancel orders?

**Comment by PaiAkshay998** [comment]
We aren't doing this. Not this year atleast.
