### ISSUE TITLE
Plot volume in stock history graphs

### ISSUE THREAD

**Issue by thakkarparth007** [delta/dalal-street-server#199]
Also change the styling of the line graph. It's honestly terrible.

Volume already arrives with the stock history data, but doesn't get plotted. It'll be cool to show the volume on the charts as well to show which periods are most active, etc.

**Comment by PaiAkshay998** [comment]
This sort of depends. Could get this done once the bugs in the server get fixed.

**Comment by adwaith007** [comment]
Should the graphs be separate or is it possible to merge it into one??

**Comment by PaiAkshay998** [comment]
@thakkarparth007 @gauthamk97 ? Same graph ideally but since the scale is different what can be done?

**Comment by PaiAkshay998** [comment]
What we could probably do is, scale the volume accordingly so that we can still put it in the same graph as price but ofcourse the units for the volume make no sense but the shape of the graph will be the same.

**Comment by thakkarparth007** [comment]
If there are 2 types of data in same graph, it's typical that you have left y-axis as something, and have a right y-axis as the other thing.

See this:

<img width="309" alt="image" src="https://user-images.githubusercontent.com/747423/50762549-40502f00-1293-11e9-9989-80612bb774e6.png">

I don't know if chartjs supports this automatically by now, but there's an SO answer describing how to do that.

https://stackoverflow.com/questions/33236941/chart-js-with-dual-axis-on-bar-and-line-graph

**Comment by thakkarparth007** [comment]
Or keep them separate but close:

<img width="617" alt="image" src="https://user-images.githubusercontent.com/747423/50762741-e0a65380-1293-11e9-8264-e0e8f8303056.png">
