### ISSUE TITLE
Update Mortgage Logic

### ISSUE THREAD

**Issue by PaiAkshay998** [delta/dalal-street-server#211]
Mortgage reselling price should not be based on current price but on the price the mortgage was taken at.

**Comment by PaiAkshay998** [comment]
Well yeah basically if they stock of company ABC is at $100, and they mortgage 50 stocks, they get 50*100 = $5000 in cash. But to buy back, they need to pay the amount they got (ie. $5000) along with an interest x _on the amount they received_ (ie. $5000). So the total amount to be paid back is $5000 + x*$5000.

Currently, we are just letting them buy back at current price. So if after taking the $5000, price of company ABC fell to $50, they only have to pay 50*50 = $2500 which is half the money they took.

**Comment by PaiAkshay998** [comment]
@Harsh2098 @nimishagarwal76  27th of December.

**Comment by PaiAkshay998** [comment]
## Proposed Solution
 Add a column to MortgageDetails table to map each Mortgage entry to corresponding transaction
(or) 
Create a new MortgageTransaction table to map each transaction to the corresponding transaction

### Mortgage Action
1. Create a mortgage entry in Transactions. Create a mortgage entry in MortgageDetails and map them together. (Preferably second approach) 
2. Push Transaction to the stream

### Retrieve Action
1. User will send ```transaction_id``` when trying to retrieve.
2. Using this mapping, find out which MortgageDetail entry this TransactionId corresponds to using the mapping
3. Subtract from MortgageDetail ```stocks_in_bank```.
4. Create a new Transaction for MortgageTransaction which has _positive_ quantity and push this to stream for user to update in frontend.

### GetMortgageDetails / Get existing mortgage
1. Use MortgageDetails to populate an array of Transactions and push this to frontend.

**Comment by Harsh2098** [comment]
So here price will act as "mortgageID"?

**Comment by PaiAkshay998** [comment]
(userId, stockId, price) Will be the primary key.

**Comment by thakkarparth007** [comment]
> In that case, if user mortgages stocks at same price again, that corresponding record in MortgageDetails table will be updated.

Yup
