### ISSUE TITLE
[Orders] Cancel all non-executed orders at the end of the day

### ISSUE THREAD

**Issue by PaiAkshay998** [delta/dalal-street-server#219]
This is how the real stock market works. It could also helps us out with the pending market orders.

**Comment by PaiAkshay998** [comment]
@gauthamk97 @coderick14 Can't we just cancel orders from database manually? Seems like much less of a hassle.

**Comment by gauthamk97** [comment]
Depends. In order to cancel an order, do we have to simply change one of the values of a column (like isActive, or isClosed or something like that), or do we have to delete the record from the table? If it's the latter, I suggest we don't do it, because it's not reversible and if not done carefully, can be absolutely disastrous.

**Comment by PaiAkshay998** [comment]
Anyways, I think cancelling them is out of the picture now? Especially with the order fee. Kinda unfair to charge money for the order and cancel it later?

**Comment by thakkarparth007** [comment]
If the order fee doesn't solve the stale orders issue (and I don't think it does, it only prevents people from mindlessly placing orders. It gives no incentive to people to cancel their unmatched orders), then we _might_ have unbalanced orderbook.

Don't know how much of an issue this would be, but just got a thought, so putting it out here. Something you might want to take a look at while doing trials.

**Comment by PaiAkshay998** [comment]
Yeah the incentive to cancel unmatched orders comes from reserving stocks. That's happening too.

**Comment by PaiAkshay998** [comment]
Don't think this is going to be needed if we reserve stocks and have an order fee.
