### ISSUE TITLE
[Logs] Remove console.logs from components

### ISSUE THREAD

**Issue by PaiAkshay998** [delta/dalal-street-server#221]
Right now we have console.log statements at a large number of places. Remove the unnecessary logs like the ones that just log received data. For now, the error logs can remain.

**Comment by gauthamk97** [comment]
Has this been completed? If so, please close. And @ishanisri for future reference, please refer to your issue number in your Pull Request title (For ex : `Fixes #221`). Thus, if the PR gets merged, Github will automatically close the related issue.
