### ISSUE TITLE
[Market] Users should also be shown how much they will lose as Order Fees before placing order.

### ISSUE THREAD

**Issue by PaiAkshay998** [delta/dalal-street-server#225]
We will be adding an ```Order Fees``` where users will have to pay some fee to put their order in the table. This is non-refundable on cancellation since the whole point for adding this is for users to think a second before spamming orders. 

Currently we are showing how much a stock would cost them etc before placing orders. Now, we also need to show them how much they would be losing as ```Order Fees``` before placing orders.

**Comment by gauthamk97** [comment]
Shouldn't this be an issue in our frontend repo, not here?

**Comment by PaiAkshay998** [comment]
We sorta have all issues on the server repo itself. Just put in different projects.
