### ISSUE TITLE
[users]: Email Verification

### ISSUE THREAD

**Issue by PaiAkshay998** [delta/dalal-street-server#237]
Probably send back an email to the registered email address to confirm if valid.

**Comment by thakkarparth007** [comment]
We have pragyan verification no?

**Comment by PaiAkshay998** [comment]
But if the user did not register with pragyan, we let him register directly with us right? Don't remember clearly.  Because I remember some people had some fake email last time.

**Comment by adwaith007** [comment]
@nimishagarwal76 I guess this is also done??
