### ISSUE TITLE
Random Deadlocks while testing "PerformBuyFromExchangeTransaction"

### ISSUE THREAD

**Issue by nimishagarwal76** [delta/dalal-street-server#250]
While testing for exchange transactions, several go routines run in parallel, but in some particular order of execution, it results in failing of tests.

For same code 
 -  **FAILED**
       https://circleci.com/gh/delta/dalal-street-server/142
 -  **PASSED**
       https://circleci.com/gh/delta/dalal-street-server/143

**Comment by thakkarparth007** [comment]
Can someone rerun the test? It failed because API call to Pragyan failed.
