### ISSUE TITLE
[orders-server]: Show users reserved assets.

### ISSUE THREAD

**Issue by PaiAkshay998** [delta/dalal-street-server#261]
Currently, we are reserving cash and stocks. But there's no mechanism to show how much cash / orders were reserved apart from scrolling portfolio page. Users should be able to see these details explicitly probably in their Portfolio page.

**Comment by nimishagarwal76** [comment]
The graph in the portfolio page can have 2 tabs, one for the stocks user has and other for the stocks reserved by the user

Along with the field of cash in hand can be total, cash reserved

![whatsapp image 2019-02-09 at 3 26 17 pm](https://user-images.githubusercontent.com/37630020/52519357-1ddd7700-2c80-11e9-9793-152e1f35a691.jpeg)
