### ISSUE TITLE
[orders-web]: Cash and stock quantity not changing on cancelling orders

### ISSUE THREAD

**Issue by PaiAkshay998** [delta/dalal-street-server#264]
Cash isn’t updating when cancelling order unless refreshed
Steps to reproduce:
1. Create a market buy
2. Cancel market buy immediately
3. Cash remains un-updated

Note : Similarly, Stock worth also isn’t updated automatically when cancelling a sell order

**Comment by gauthamk97** [comment]
@PaiAkshay998 No one assigned to this?

**Comment by nimishagarwal76** [comment]
#298 resolves this, it was due to incorrect transaction being sent.
