### ISSUE TITLE
[ Registration ] Domain Filtering

### ISSUE THREAD

**Issue by nimishagarwal76** [delta/dalal-street-server#290]
To prevent fake emails from registration and misusing the platform, we need to allow only certain domains for registration.

**Comment by nimishagarwal76** [comment]
https://www.favor.com.ua/en/banned-email-domains/
https://gist.github.com/michenriksen/8710649

http://api.antideo.com/email/jilmotorzu@enayu.com
This api works pretty well for the recent websites also. Need to figure out how many free calls does it support.

List of most common disposable email domains.

 We can only blacklist domains. Only allowing certain domains will limit the audience from other colleges.
But a new disposable service popup every day so its difficult to blacklist them.

**Comment by adwaith007** [comment]
so are we doing this??

**Comment by nimishagarwal76** [comment]
No otp handles it.
