### ISSUE TITLE
[Feature]: Add forgot password option.

### ISSUE THREAD

**Issue by adwaith007** [delta/dalal-street-server#294]
Since we are implementing browser fingerprint and restricting the user from making a new account. We need to implement the reset password option.

**Comment by nimishagarwal76** [comment]
**FLOW**

USER
- User clicks Forgot password in the frontend and get redirected to the forgot password page
- They enter their email id and a mail would be sent to their corresponding id
- They click the mail, which gives them the option to enter new password.

SYSTEM
- Create a table PasswordChangeRequests
- 3 columns : id, Time, userId

We will be following - 
https://stackoverflow.com/a/1102817/9794090

Follow the approach. Regarding the hash function, you can look for the Email Verification code. Send mail using sendgrid only in Docker Environment.
Server runs on port - 8000 by default. So you for new password you can even write a simple static page and serve at server port itself
