### ISSUE TITLE
Make mortgage involve interests

### ISSUE THREAD

**Issue by thakkarparth007** [delta/dalal-street-server#69]
Currently mortgaging doesn't require users to pay any interest. It'd be fun to have them pay interest as well. Need to think this through.

**Comment by PaiAkshay998** [comment]
I think this would be a nice thing to have this time. Lot of different things can be tried out; variable interest rate depending on how large the amount is or some constant interest rate.

**Comment by PaiAkshay998** [comment]
@nimishagarwal76 , @Harsh2098 1st of Jan

**Comment by PaiAkshay998** [comment]
#236 I think this solves the problem of adjusting game difficulty better than this? @thakkarparth007
