### ISSUE TITLE
Price Alerts UI on Frontend

### ISSUE THREAD

**Issue by thakkarparth007** [delta/dalal-street-server#89]

**Comment by PaiAkshay998** [comment]
Right now, there's literally nothing on the page that indicates that the price of a stock has changed. other than the change in the numerical value of the price. 

https://pro.coinbase.com/trade/BTC-USD

Check out this site. The order book column shows orders that are pending. Every time an order gets completed, there's this sort of flash / blinking of that particular order which is much more easier to see and gives a clear indication that an order has been carried out and the price is going to change. We need something like that.

**Comment by PaiAkshay998** [comment]
@ishanisri finish this by 28th of December.
